### application properties ###
spring.application.name=momentumapi
server.port=8080

### database properties ###
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

### Hibernate properties ###
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

### Flyway properties ###
spring.flyway.enabled=true
#spring.flyway.url=${POSTGRES_URL}
#spring.flyway.user=${POSTGRES_USER}
#spring.flyway.password=${POSTGRES_PASSWORD}
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true

### JWT properties ###
jwt.secret=${JWT_SECRET}
jwt.expirationTime=${JWT_EXPIRATION_TIME}

### logging properties ###
logging.level.org.hibernate=DEBUG
logging.level.org.springframework.transaction=DEBUG

### mail properties ###
spring.mail.host=smtp.gmail.com
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

### CloudAMQP properties ###
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.virtual-host=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.listener.simple.auto-startup=true
messaging.emailQueue=${EMAIL_QUEUE}

