# application properties
spring.application.name=momentumapi
server.port=9090

# database properties
spring.datasource.url=jdbc:mysql://localhost:3306/momentum_db
spring.datasource.username=root
spring.datasource.password=musadzeyt
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true

# JWT properties
jwt.secret=FqeR7gYNeNEhk57e6PWAdl5b8FyK963VxEL8SKeuFci8quPYdVHszTzxRVYxI1z8Jnuu2waBQj8pCbzC+ONq0w==
jwt.expirationTime=3600000
