### application properties ###
server.port=8080

### database properties ###
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

### Hibernate properties ###
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

### JWT properties ###
jwt.secret=${JWT_SECRET}
jwt.expirationTime=${JWT_EXPIRATION_TIME}

### logging properties ###
logging.level.org.hibernate=DEBUG
logging.level.org.springframework.transaction=DEBUG
