### application properties ###
spring.application.name=momentumapi
server.port=8080

### database properties ###
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

### Hibernate properties ###
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

### JWT properties ###
jwt.secret=${JWT_SECRET}
jwt.expirationTime=${JWT_EXPIRATION_TIME}

### logging properties ###
logging.level.org.hibernate=DEBUG
logging.level.org.springframework.transaction=DEBUG

### mail properties ###
spring.mail.host=smtp.gmail.com
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

### CloudAMQP properties ###
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.virtualHost=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.listener.simple.auto-startup=false
messaging.queueName=EmailQueue

